import { getGeminiClient } from "@/lib/gemini";
import { ASSISTANT_SYSTEM_PROMPT } from "@/prompts/assistant";
import { logger } from "@/lib/logger";

interface ChatMessage {
  role: "user" | "model";
  content: string;
}

export class AiAssistantService {
  static async ask(
    contextSnapshot: string,
    history: ChatMessage[],
    userQuery: string
  ): Promise<string> {
    const ai = getGeminiClient();
    if (!ai) {
      return "Sentinel AI assistant is currently disabled or Gemini API Key is not set in environment configurations.";
    }

    try {
      const systemInstruction = ASSISTANT_SYSTEM_PROMPT.replace(
        "${contextSnapshot}",
        contextSnapshot
      );

      // Simple history mapping matching GoogleGenAI format
      const contents = history.map((h) => ({
        role: h.role,
        parts: [{ text: h.content }],
      }));

      // Add the final user query
      contents.push({
        role: "user",
        parts: [{ text: userQuery }],
      });

      logger.info(`Sending assistant query with ${history.length} messages of context memory`);
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents,
        config: {
          systemInstruction,
        },
      });

      return response.text || "No response generated by Sentinel AI.";
    } catch (error) {
      logger.error("Error invoking Gemini assistant:", error);
      return "I encountered an error analyzing your request. Please try again. Technical details: " + (error instanceof Error ? error.message : String(error));
    }
  }
}
